"use client";

import Image from 'next/image';

export default function ProjectsPage() {

  const projects = [
    {
      id: 1,
      original: "/images/original1.jpg",
      generated: "/images/generated1.jpg",
      title: "Living Room Design",
    },
    {
      id: 2,
      original: "/images/original2.jpg",
      generated: "/images/generated2.jpg",
      title: "Bedroom Design",
    },
    {
      id: 3,
      original: "/images/original3.jpg",
      generated: "/images/generated3.jpg",
      title: "Dining Room Design",
    },
    {
      id: 4,
      original: "/images/original4.jpg",
      generated: "/images/generated4.jpg",
      title: "Office Design",
    },
  ];

  return (
    <main className="flex min-h-screen flex-col py-10 lg:pl-72 bg-gray-100">
      {/* Page Header */}
      <div className="text-center">
        <h1 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-pink-500 via-yellow-500 to-indigo-500 mb-6">
          Project Showcase
        </h1>
        <p className="text-lg text-gray-600 mb-10">
          Here are the before and after examples of the interior designs generated by our AI.
        </p>
      </div>

      {/* Cards Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-12 px-6 lg:px-8">
        {projects.map((project) => (
          <div
            key={project.id}
            className="rounded-lg shadow-lg overflow-hidden bg-gradient-to-b from-purple-900 via-indigo-900 to-blue-900 text-white transform transition duration-300 hover:scale-105"
          >
            <div className="relative">
              <h3 className="text-2xl font-bold text-white px-4 pt-4">
                {project.title}
              </h3>

              <div className="mt-4 px-4">
                <p className="text-sm font-semibold text-gray-300">Original</p>
                <Image
                  src={project.original}
                  alt={`${project.title} Original`}
                  width={800}  // Increased the image width
                  height={600} // Increased the image height
                  className="w-full h-64 object-cover rounded-md shadow-md"
                />
              </div>

              <div className="mt-4 px-4 pb-4">
                <p className="text-sm font-semibold text-gray-300">AI Generated</p>
                <Image
                  src={project.generated}
                  alt={`${project.title} AI Generated`}
                  width={800}  // Increased the image width
                  height={600} // Increased the image height
                  className="w-full h-64 object-cover rounded-md shadow-md"
                />
              </div>
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
